### ISSUE TITLE
hello build error

### ISSUE THREAD

**Issue by chongbo2013** [jsomedon/build_aseprite_on_mac.sh#1]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3191545/167658707-b04b5264-04ea-404e-a182-858f95c2fd99.png">

**Comment by jsomedon** [comment]
Just by looking at your screenshot, it looks like you didn't install necessary dependencies. My script should have told you which dependencies users need.. I will fix that in a moment.

---EDIT---

Fixed. Should work now.
